<img src="images/usm.jpg" width="480" height="240" align="left"/>

# MAT281 - Laboratorio N°02

## Objetivos de la clase

* Reforzar los conceptos básicos de numpy.

## Contenidos

* [Problema 01](#p1)
* [Problema 02](#p2)
* [Problema 03](#p3)

<a id='p1'></a>

## Problema 01

Una **media móvil simple** (SMA) es el promedio de los últimos $k$ datos anteriores, es decir, sea $a_1$,$a_2$,...,$a_n$ un arreglo $n$-dimensional, entonces la SMA se define por:

$$sma(k) =\dfrac{1}{k}(a_{n}+a_{n-1}+...+a_{n-(k-1)}) = \dfrac{1}{k}\sum_{i=0}^{k-1}a_{n-i}  $$ 


Por otro lado podemos definir el SMA con una venta móvil de $n$ si el resultado nos retorna la el promedio ponderado avanzando de la siguiente forma:

* $a = [1,2,3,4,5]$, la SMA con una ventana de $n=2$ sería:


    * sma(2): [mean(1,2),mean(2,3),mean(3,4)] = [1.5, 2.5, 3.5, 4.5]
    * sma(3): [mean(1,2,3),mean(2,3,4),mean(3,4,5)] = [2.,3.,4.]


Implemente una función llamada `sma` cuyo input sea un arreglo unidimensional $a$ y un entero $n$, y cuyo ouput retorne el valor de la media móvil simple sobre el arreglo de la siguiente forma:

* **Ejemplo**: *sma([5,3,8,10,2,1,5,1,0,2], 2)* = $[4. , 5.5, 9. , 6. , 1.5, 3. , 3. , 0.5, 1. ]$

En este caso, se esta calculando el SMA para un arreglo con una ventana de $n=2$.

**Hint**: utilice la función `numpy.cumsum`

In [65]:
import numpy as np

In [66]:
def sma(a, n) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

In [67]:
a=[5,3,8,10,2,1,5,1,0,2]
n=2

In [69]:
sma(a, n)

array([4. , 5.5, 9. , 6. , 1.5, 3. , 3. , 0.5, 1. ])

<a id='p2'></a>

## Problema 02

La función **strides($a,n,p$)**, corresponde a transformar un arreglo unidimensional $a$ en una matriz de $n$ columnas, en el cual las filas se van construyendo desfasando la posición del arreglo en $p$ pasos hacia adelante.

* Para el arreglo unidimensional $a$ = [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], la función strides($a,4,2$), corresponde a crear una matriz de $4$ columnas, cuyos desfaces hacia adelante se hacen de dos en dos. 

El resultado tendría que ser algo así:$$\begin{pmatrix}
 1& 2 &3 &4 \\ 
 3&  4&5&6 \\ 
 5& 6 &7 &8 \\ 
 7& 8 &9 &10 \\ 
\end{pmatrix}$$


Implemente una función llamada `strides(a,4,2)` cuyo input sea un arreglo unidimensional y retorne la matriz de $4$ columnas, cuyos desfaces hacia adelante se hacen de dos en dos. 

* **Ejemplo**: *strides($a$,4,2)* =$\begin{pmatrix}
 1& 2 &3 &4 \\ 
 3&  4&5&6 \\ 
 5& 6 &7 &8 \\ 
 7& 8 &9 &10 \\ 
\end{pmatrix}$


In [53]:
import numpy as np

In [58]:
𝑎  = np.array([ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print (a)

[ 1  2  3  4  5  6  7  8  9 10]


In [59]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [84]:
fila 

3.0

In [24]:
a[-1]

10

In [100]:
a[0]
a[4]

5

In [170]:
def strides(a,n,p):
    c=a[-1]
    fila=int((c-n)/p)
    b=np.zeros((fila+1,n))
    contador=0
    matri=[]
    for i in range(0,fila+1):        
        b[i][:]=a[contador:contador+n]
        contador=contador+p
    return b

In [171]:
strides(a,4,2)

array([[ 1.,  2.,  3.,  4.],
       [ 3.,  4.,  5.,  6.],
       [ 5.,  6.,  7.,  8.],
       [ 7.,  8.,  9., 10.]])

<a id='p3'></a>

## Problema 03


Un **cuadrado mágico** es una matriz de tamaño $n \times n$ de números enteros positivos tal que 
la suma de los números por columnas, filas y diagonales principales sea la misma. Usualmente, los números empleados para rellenar las casillas son consecutivos, de 1 a $n^2$, siendo $n$ el número de columnas y filas del cuadrado mágico.

Si los números son consecutivos de 1 a $n^2$, la suma de los números por columnas, filas y diagonales principales 
es igual a : $$M_{n} = \dfrac{n(n^2+1)}{2}$$
Por ejemplo, 

* $A= \begin{pmatrix}
 4& 9 &2 \\ 
 3&  5&7 \\ 
 8& 1 &6 
\end{pmatrix}$,
es un cuadrado mágico.

* $B= \begin{pmatrix}
 4& 2 &9 \\ 
 3&  5&7 \\ 
 8& 1 &6 
\end{pmatrix}$, no es un cuadrado mágico.

Implemente una función llamada `es_cudrado_magico` cuyo input sea una matriz cuadrada de tamaño $n$ con números consecutivos de $1$ a $n^2$ y cuyo ouput retorne *True* si es un cuadrado mágico o 'False', en caso contrario

* **Ejemplo**: *es_cudrado_magico($A$)* = True, *es_cudrado_magico($B$)* = False

**Hint**: Cree una función que valide la mariz es cuadrada y  que sus números son consecutivos del 1 a $n^2$.

In [1]:
matriz=[[4,9,2],[3,5,7],[8,1,6]]

In [2]:
def es_cuadrado_magico (matriz) :
	N = len(matriz[0])
	sumas = []
	for i in range (N) :
		suma = 0
		for j in range (N) :
			suma += matriz[i][j]
		sumas.append (suma)
	for j in range (N) :
		suma = 0
		for i in range (N) :
			suma += matriz[i][j]
		sumas.append (suma)
	suma = 0
	for k in range (N):
		suma += matriz[k][k]
	sumas.append (suma)
	suma = 0
	for j in range (N):
		i = N - 1 - j
		suma += matriz[i][j]
	sumas.append (suma)
	ultimaSuma = sumas[0]
	for suma in sumas :
		if ultimaSuma != suma :
			return False
		ultimaSuma = suma
	return True

In [3]:
es_cuadrado_magico(matriz)

True

In [4]:
matriz2=[[4,2,9],[3,5,7],[8,1,6]]

In [5]:
es_cuadrado_magico(matriz2)

False